
spring:
  datasource.url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  datasource.username: sa
  datasource.password: sa
  datasource.driver-class-name: org.h2.Driver
  liquibase.change-log: db/changelog/db.changelog-master.xml
  h2.console.enabled: true
  jpa.show-sql: true
  activemq.in-memory: true
  activemq.pool.enabled: false
  activemq.packages.trust-all: true
server.port: 9000