spring:
  application.name: spring-app
  profiles.active: dev
  datasource.url: jdbc:h2:mem:testdb
  datasource.driverClassName: org.h2.Driver
  datasource.username: sa
  datasource.password: sa
  liquibase.change-log: db/changelog/db.changelog-master.xml
  jpa.show-sql: true
server.port: 9000

catalog.address: http://localhost:9001